import type { NextPage } from 'next'
import Head from 'next/head'
import { useEffect } from 'react';

import { setupGame } from '../helper';

const Home: NextPage = () => {
  useEffect(() => {
    setupGame();
  }, []);

  return (
    <div >
      <Head>
        <title>Infinite Plants</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="game-container">
        <h1>Infinite Plants</h1>
      </div>
    </div>
  )
}

export default Home
